pub mod adaptation;
pub mod ade;
pub mod analysis;
pub mod analysis_audit;
pub mod analysis_fetch;
pub(crate) mod analyze_training;
pub mod changepoint;
pub mod coach_guidance;
pub mod coach_metrics;
pub mod coach_metrics_constants;
pub mod cp_regression;
pub mod dedupe;
pub(crate) mod endurance_evidence;
pub(crate) mod endurance_evidence_fetch;
pub mod fetch_error;
pub(crate) mod fitness_context;
pub mod forecast;
pub mod interval_analysis;
pub mod interval_segment_metrics;
pub(crate) mod metric_streams;
pub mod progress_tracking;
pub mod race_readiness;
pub mod recovery_assessment_engine;
pub mod shared;
pub mod trail_execution;
pub mod traits;

pub use analysis::{AnalysisEngine, WorkoutInsights};
